#! /usr/bin/python3

import spidev
import ctypes

spi = spidev.SpiDev()
spi.open(0,0)
spi.max_speed_hz = 10000
spi.mode = 0

PACKETSIZE = 128

def CalculateChecksum(packet_bytes):
    cs = 0
    for b in packet_bytes[:-1]:
        cs ^= b
    return cs

class ServoCmd_t(ctypes.Structure):
    _fields_ = [
        ("amplitude", ctypes.c_float),
        ("speed", ctypes.c_uint16),
        ("horz_offset", ctypes.c_int16),
        ("vert_offset", ctypes.c_int16),
    ]

class ThrusterCmd_t(ctypes.Structure): 
    _fields_ = [
        ("thrust", ctypes.c_int8),
    ]

class IMUCom_t(ctypes.Structure): 
    _fields_ = [
        ("acc_x", ctypes.c_float),
        ("acc_y", ctypes.c_float),
        ("acc_z", ctypes.c_float),
        ("gyro_x", ctypes.c_float),
        ("gyro_y", ctypes.c_float),
        ("gyro_z", ctypes.c_float),
    ]

class MagCom_t(ctypes.Structure):
    _fields_ = [
        ("head_x", ctypes.c_float),
        ("head_y", ctypes.c_float),
        ("head_z", ctypes.c_float),
    ]

class Bar30Com_t(ctypes.Structure):
    _fields_ = [
        ("pressure", ctypes.c_float),
        ("water_temp", ctypes.c_float),
    ]

class HumidCom_t(ctypes.Structure):
    _fields_ = [
        ("humidity", ctypes.c_float),
        ("air_temp", ctypes.c_float),
    ]

class BoardCom_t(ctypes.Structure):
    _fields_ = [
        ("board_temp", ctypes.c_float),
    ]

class InPacket(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ("SoP", ctypes.c_uint8*2),
        ("pad0", ctypes.c_uint8*2), # mimic STM32 padding
        ("IMUCom", IMUCom_t),
        ("MagCom", MagCom_t),
        ("Bar30Com", Bar30Com_t),
        ("HumidCom", HumidCom_t),
        ("BoardCom", BoardCom_t),
        ("CheckSum", ctypes.c_uint8),
        ("pad1", ctypes.c_uint8), # bring size to 64 bytes total
    ]

class OutPacket(ctypes.Structure):
    _fields_ = [
        ("SoP", ctypes.c_uint8*2),
        ("pad0", ctypes.c_uint8*2), # mimic STM32 padding
        ("ServoCmd", ServoCmd_t*8),
        ("ThrusterCmd", ThrusterCmd_t),
        ("CheckSum", ctypes.c_uint8),
        ("pad1", ctypes.c_uint8),
    ]


out = OutPacket()

# Fill in dummy commands
for i in range(8):
    out.ServoCmd[i].amplitude = 80
    out.ServoCmd[i].speed = 1
    out.ServoCmd[i].horz_offset = 0
    out.ServoCmd[i].vert_offset = 0

out.ThrusterCmd.thrust = 50
out.SoP[0] = 0xAA
out.SoP[1] = 0x55
out.CheckSum = CalculateChecksum(bytearray(out))

packet_bytes = ctypes.string_at(ctypes.byref(out), ctypes.sizeof(out))

size = ctypes.sizeof(out)
if size > PACKETSIZE:
    raise ValueError("OutPacket too large!")

tx = bytearray(PACKETSIZE)
tx[:size] = packet_bytes

rx = bytearray(128)
packet_len = ctypes.sizeof(InPacket)

while (1):
    # rx.extend(spi.readbytes(32))
    # rx.extend(spi.xfer2([0x00] * 32))
    rx.extend(spi.xfer2(tx))
    while (len(rx) >= PACKETSIZE):
        if (rx[0] == 0xAA and rx[1] == 0x55):
            packet_bytes = rx[:PACKETSIZE]
            packet = InPacket.from_buffer_copy(packet_bytes)

            checksum_bytes = ctypes.string_at(ctypes.byref(packet), packet_len - 1)
            cs = CalculateChecksum(checksum_bytes)
            if (cs != packet.CheckSum):
                print(f"ERROR: CheckSum failed | got {packet.CheckSum}, calculated {cs}\n")
            else:
                print(f"CheckSum OK: {cs}")
                print(f"    IMU:")
                print(f"        acc_x: {packet.IMUCom.acc_x}")
                print(f"        acc_y: {packet.IMUCom.acc_y}")
                print(f"        acc_z: {packet.IMUCom.acc_z}")
                print(f"        gyro_x: {packet.IMUCom.gyro_x}")
                print(f"        gyro_y: {packet.IMUCom.gyro_y}")
                print(f"        gyro_z: {packet.IMUCom.gyro_z}")
                print(f"    Magnetometer:")
                print(f"        head_x: {packet.MagCom.head_x}")
                print(f"        head_y: {packet.MagCom.head_y}")
                print(f"        head_z: {packet.MagCom.head_z}")
                print(f"    Bar30:")
                print(f"        pressure: {packet.Bar30Com.pressure}")
                print(f"        water_temp: {packet.Bar30Com.water_temp}")
                print(f"    Humidity:")
                print(f"        humidity: {packet.HumidCom.humidity}")
                print(f"        air_temp: {packet.HumidCom.air_temp}")
                print(f"    Board Temp:")
                print(f"        board_temp: {packet.BoardCom.board_temp}")
                print(f"    Check Sum:")
                print(f"        sum: {packet.CheckSum}\n")
                
                rx = rx[PACKETSIZE:]
        else:
            rx.pop(0)

spi.close()

