// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ControlMessage.proto
// Protobuf C++ Version: 7.34.1

#include "ControlMessage.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ControlMessage {

inline constexpr ControlMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        forward_{0},
        pitch_{0},
        roll_{0},
        thrust_{0} {}

template <typename>
constexpr ControlMessage::ControlMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ControlMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct ControlMessageDefaultTypeInternal {
  constexpr ControlMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ControlMessageDefaultTypeInternal() {}
  union {
    ControlMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ControlMessageDefaultTypeInternal _ControlMessage_default_instance_;
}  // namespace ControlMessage
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_ControlMessage_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_ControlMessage_2eproto = nullptr;
const ::uint32_t
    TableStruct_ControlMessage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ControlMessage::ControlMessage, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ControlMessage::ControlMessage, _impl_.forward_),
        PROTOBUF_FIELD_OFFSET(::ControlMessage::ControlMessage, _impl_.pitch_),
        PROTOBUF_FIELD_OFFSET(::ControlMessage::ControlMessage, _impl_.roll_),
        PROTOBUF_FIELD_OFFSET(::ControlMessage::ControlMessage, _impl_.thrust_),
        0,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::ControlMessage::ControlMessage)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::ControlMessage::_ControlMessage_default_instance_._instance,
};
const char descriptor_table_protodef_ControlMessage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024ControlMessage.proto\022\016ControlMessage\"N"
    "\n\016ControlMessage\022\017\n\007Forward\030\001 \001(\002\022\r\n\005Pit"
    "ch\030\002 \001(\002\022\014\n\004Roll\030\003 \001(\002\022\016\n\006Thrust\030\004 \001(\002b\006"
    "proto3"
};
static ::absl::once_flag descriptor_table_ControlMessage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ControlMessage_2eproto = {
    false,
    false,
    126,
    descriptor_table_protodef_ControlMessage_2eproto,
    "ControlMessage.proto",
    &descriptor_table_ControlMessage_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_ControlMessage_2eproto::offsets,
    file_level_enum_descriptors_ControlMessage_2eproto,
    file_level_service_descriptors_ControlMessage_2eproto,
};
namespace ControlMessage {
// ===================================================================

class ControlMessage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ControlMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_._has_bits_);
};

ControlMessage::ControlMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ControlMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ControlMessage.ControlMessage)
}
ControlMessage::ControlMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ControlMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ControlMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE ControlMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ControlMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, forward_),
           0,
           offsetof(Impl_, thrust_) -
               offsetof(Impl_, forward_) +
               sizeof(Impl_::thrust_));
}
ControlMessage::~ControlMessage() {
  // @@protoc_insertion_point(destructor:ControlMessage.ControlMessage)
  SharedDtor(*this);
}
inline void ControlMessage::SharedDtor(MessageLite& self) {
  ControlMessage& this_ = static_cast<ControlMessage&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ControlMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ControlMessage(arena);
}
constexpr auto ControlMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ControlMessage),
                                            alignof(ControlMessage));
}
constexpr auto ControlMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ControlMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &ControlMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ControlMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ControlMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ControlMessage>(), &ControlMessage::ByteSizeLong,
              &ControlMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_._cached_size_),
          false,
      },
      &ControlMessage::kDescriptorMethods,
      &descriptor_table_ControlMessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ControlMessage_class_data_ =
        ControlMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ControlMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ControlMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ControlMessage_class_data_.tc_table);
  return ControlMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
ControlMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ControlMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ControlMessage::ControlMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float Thrust = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0,
      PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.thrust_)}},
    // float Forward = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 0, 0,
      PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.forward_)}},
    // float Pitch = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0,
      PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.pitch_)}},
    // float Roll = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0,
      PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.roll_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float Forward = 1;
    {PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.forward_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float Pitch = 2;
    {PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.pitch_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float Roll = 3;
    {PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.roll_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float Thrust = 4;
    {PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.thrust_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ControlMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:ControlMessage.ControlMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    ::memset(&_impl_.forward_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.thrust_) -
        reinterpret_cast<char*>(&_impl_.forward_)) + sizeof(_impl_.thrust_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ControlMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ControlMessage& this_ = static_cast<const ControlMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ControlMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ControlMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:ControlMessage.ControlMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // float Forward = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_forward()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          1, this_._internal_forward(), target);
    }
  }

  // float Pitch = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_pitch()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_pitch(), target);
    }
  }

  // float Roll = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_roll()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          3, this_._internal_roll(), target);
    }
  }

  // float Thrust = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_thrust()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          4, this_._internal_thrust(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ControlMessage.ControlMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ControlMessage::ByteSizeLong(const MessageLite& base) {
  const ControlMessage& this_ = static_cast<const ControlMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ControlMessage::ByteSizeLong() const {
  const ControlMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ControlMessage.ControlMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // float Forward = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_forward()) != 0) {
        total_size += 5;
      }
    }
    // float Pitch = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_pitch()) != 0) {
        total_size += 5;
      }
    }
    // float Roll = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_roll()) != 0) {
        total_size += 5;
      }
    }
    // float Thrust = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_thrust()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ControlMessage::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ControlMessage*>(&to_msg);
  auto& from = static_cast<const ControlMessage&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:ControlMessage.ControlMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_forward()) != 0) {
        _this->_impl_.forward_ = from._impl_.forward_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_pitch()) != 0) {
        _this->_impl_.pitch_ = from._impl_.pitch_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_roll()) != 0) {
        _this->_impl_.roll_ = from._impl_.roll_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_thrust()) != 0) {
        _this->_impl_.thrust_ = from._impl_.thrust_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ControlMessage::CopyFrom(const ControlMessage& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:ControlMessage.ControlMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ControlMessage::InternalSwap(ControlMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.thrust_)
      + sizeof(ControlMessage::_impl_.thrust_)
      - PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.forward_)>(
          reinterpret_cast<char*>(&_impl_.forward_),
          reinterpret_cast<char*>(&other->_impl_.forward_));
}

::google::protobuf::Metadata ControlMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ControlMessage
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_ControlMessage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
